### ISSUE TITLE
request to overledger api gets failed due to timeout

### ISSUE THREAD

**Issue by anshuman-singh-93** [quantnetwork/overledger-sdk-javascript#14]
I checked the source code and found out that in axios configuration, timout value is set to 1000 ms which leads to request timeout instantly.

**Comment by anshuman-singh-93** [comment]
I think configurable timeout will be good to have for poor connections.  though I was on good bandwidth still approx 3 out of 10  request was getting failed.

**Comment by jeanpauldejong** [comment]
Ok, we will do that unless @oktapodia or @ddimas-quant  have another view.

We've reviewed the logs and performance and can't replicate that but will keep an eye out for it.
