### ISSUE TITLE
OverledgerSDK is not a constructor

### ISSUE THREAD

**Issue by anshuman-singh-93** [quantnetwork/overledger-sdk-javascript#15]
I have used following line  as documented

`const overledger = new OverledgerSDK("mappId", "bpiKey", {
  dlts: [{ dlt: "bitcoin" }, { dlt: "ethereum" }, { dlt: "ripple" }]
});`

but it throws error "OverledgerSDK " is not a constructor. so i dug into the source code and figured out that its exporting default propoerty.
so i had to use like this to make it work-

`const overledger = new OverledgerSDK.default("mappId", "bpiKey", {
  dlts: [{ dlt: "bitcoin" }, { dlt: "ethereum" }, { dlt: "ripple" }]
});`

**Comment by oktapodia** [comment]
Thanks for your report @anshuman-singh-93
