### ISSUE TITLE
readTransactionsByMappId/readByTransactionId  giving server error

### ISSUE THREAD

**Issue by anshuman-singh-93** [quantnetwork/overledger-sdk-javascript#20]
readTransactionsByMappId/readByTransactionId method returns error with status code 500 but the error is silently dropped and appear as success because this method is wrapped inside try/catch. end user will never know if there was any error while calling this method

snippet-

    public async readByTransactionId(ovlTransactionId: string): Promise<Object> 
    {
      try {
        const response = await this.request.get(${this.overledgerUri}/transactions/${ovlTransactionId});
        return response.data;
      } catch (e) {
        return e.response.data;
    }}

shouln't it be like this so that user can know if there was any error

     public async readByTransactionId(ovlTransactionId: string): Promise<Object>
     {
       return await this.request.get(${this.overledgerUri}/transactions/${ovlTransactionId});
     }

**Comment by jeanpauldejong** [comment]
[ch1334] Investigating

**Comment by oktapodia** [comment]
Thank you for your issue @anshuman-singh-93 we are investigating that.

Your suggestion confirmed our thought, we will update the handling way soon-ish

**Comment by oktapodia** [comment]
It has been deployed with the v1.0.0-alpha.7 version
